name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag traefik-forward-auth:2.3.0
      - name: Push
        run: docker push ghcr.io/gabrielpetry/traefik-forward-auth:latest
